FROM mcr.microsoft.com/devcontainers/base:alpine-3.21

RUN apk update && \
    apk add --no-cache \
    shfmt \
    chezmoi \
    starship \
    eza \
    bat \
    curl \
    git \
    vim \
    fastfetch \
    fzf \
    fd \
    ripgrep \
    neovim \
    bottom \
    fish \
    zoxide \
    zsh && \
    apk upgrade --no-cache
